"""Persistence interfaces — implementations live in separate files per backend."""

from pathlib import Path
from typing import Optional, Protocol

from fastapi import UploadFile

from app.models.domain.document import DocumentMetadata, StoredDocument
from app.models.domain.email import InboundAddress
from app.models.domain.run import RunResult
from app.models.domain.template import PipelineTemplate
from app.models.domain.upload import UploadRecord
from app.models.domain.user import UserRecord
from app.models.domain.user_template_version import RefinementEvent, UserTemplateVersionRecord
from app.models.domain.workflow import WorkflowRecord, WorkflowSummary


class DataRepository(Protocol):
    """Users, workflows, and runs — Postgres, in-memory, etc."""

    @property
    def backend_name(self) -> str:
        """e.g. 'memory' or 'supabase'."""

    def health_check(self) -> tuple[bool, str]:
        """Return (ok, detail_message)."""

    def save_user(self, user: UserRecord) -> None: ...
    def get_user(self, user_id: str) -> Optional[UserRecord]: ...
    def get_user_by_email(self, email: str) -> Optional[UserRecord]: ...
    def list_users(self) -> list[UserRecord]: ...

    def save_run(self, run: RunResult) -> None: ...
    def get_run(self, run_id: str) -> Optional[RunResult]: ...
    def list_runs_by_workflow(self, workflow_id: str) -> list[RunResult]: ...
    def list_runs_by_status(self, status: str) -> list[RunResult]: ...
    def count_child_runs(self, parent_run_id: str) -> int: ...

    def save_workflow(self, workflow: WorkflowRecord) -> None: ...
    def get_workflow(self, workflow_id: str) -> Optional[WorkflowRecord]: ...
    def list_workflows(self, user_id: Optional[str] = None) -> list[WorkflowSummary]: ...
    def delete_workflow(self, workflow_id: str) -> None: ...

    def save_template_version(self, version: UserTemplateVersionRecord) -> None: ...
    def get_template_version(self, version_id: str) -> Optional[UserTemplateVersionRecord]: ...
    def list_template_versions(
        self, scope_type: str, scope_id: str
    ) -> list[UserTemplateVersionRecord]: ...
    def save_refinement_event(self, event: RefinementEvent) -> None: ...
    def list_refinement_events(
        self, template_id: Optional[str] = None, limit: int = 100
    ) -> list[RefinementEvent]: ...

    def save_inbound_address(self, address: InboundAddress) -> None: ...
    def get_inbound_address(self, address_id: str) -> Optional[InboundAddress]: ...
    def get_inbound_address_for_workflow(
        self, workflow_id: str
    ) -> Optional[InboundAddress]: ...
    def list_inbound_addresses(self, user_id: str) -> list[InboundAddress]: ...
    def delete_inbound_address(self, address_id: str) -> None: ...

    def save_upload(self, upload: UploadRecord) -> None: ...
    def get_upload(self, upload_id: str) -> Optional[UploadRecord]: ...


class TemplateRepository(Protocol):
    """Pipeline template catalog — Postgres or in-memory seeds."""

    @property
    def backend_name(self) -> str:
        """e.g. 'memory' or 'supabase'."""

    def list_templates(
        self,
        *,
        category: Optional[str] = None,
        active_only: bool = True,
    ) -> list[PipelineTemplate]: ...

    def get_template(self, template_id: str) -> Optional[PipelineTemplate]: ...

    def save_template(self, template: PipelineTemplate) -> PipelineTemplate: ...


class DocumentStorageRepository(Protocol):
    """Uploaded file bytes — local disk, Supabase Storage, S3, etc."""

    @property
    def backend_name(self) -> str:
        """e.g. 'local' or 'supabase'."""

    async def save_document(self, upload_id: str, file: UploadFile) -> StoredDocument: ...
    async def save_document_bytes(
        self, upload_id: str, filename: str, content: bytes, content_type: str
    ) -> StoredDocument: ...
    async def list_documents(self, upload_id: str) -> list[DocumentMetadata]: ...
    async def upload_exists(self, upload_id: str) -> bool: ...
    async def materialize_path(self, upload_id: str, document_id: str) -> Path: ...
    def release_path(self, path: Path) -> None: ...
    async def read_bytes(self, upload_id: str, document_id: str) -> bytes: ...


class UserTemplateStorageRepository(Protocol):
    """User template version payloads — local disk, Supabase Storage, or AWS S3."""

    @property
    def backend_name(self) -> str:
        """e.g. 'local', 'supabase', or 'aws_s3'."""

    def build_storage_key(self, scope_type: str, scope_id: str, version_id: str) -> str: ...
    def save_version(self, storage_key: str, payload: dict) -> str: ...
    def load_version(self, storage_key: str) -> dict: ...
    def delete_version(self, storage_key: str) -> None: ...
